// src/app/layout.js

import "./globals.css"; // hoặc import css của bạn

export const metadata = {
  title: "Skibidi AI",
  description: "Generated by Skibidi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
